dist: trusty

language: rust
rust:
    - stable
    #- beta
    #- nightly

cache:
  directories:
    - $HOME/.cargo

sudo: false

before_script:
  - cargo install cobalt-bin || true
  - export PATH="$PATH:/home/travis/.cargo/bin"

script:
  - cobalt build

after_success: |
  [ $TRAVIS_BRANCH = source ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  git config user.name "BennyYip" &&
  git config user.email "yebenmy@protonmail.com"

deploy:
  github_token: $GH_TOKEN
  local_dir: ./build/
  provider: pages
  skip_cleanup: true
  target_branch: master
  on:
    branch: source

