dist: trusty
sudo: false

before_script:
  - curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs --crate cobalt --force --target x86_64-unknown-linux-gnu
  - export PATH="$PATH:/home/travis/.cargo/bin"

script:
  - cobalt build

after_success: |
  [ $TRAVIS_BRANCH = source ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cobalt import --branch master &&
  git show-ref &&
  git config user.name "BennyYip" &&
  git config user.email "yebenmy@protonmail.com" &&
  git push -fq https://${GH_TOKEN}@github.com/bennyyip/bennyyip.github.io.git master
